services:

  movewiz-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file: stack.env
    ports:
      - '3000:3000'
    restart: unless-stopped

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    environment:
      - MARIADB_USER=user
      - MARIADB_PASSWORD=mypswd
      - MARIADB_DATABASE=my_db
      - MARIADB_ROOT_PASSWORD=rootpswd
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql/

volumes:
  mariadb_data:
